// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_table.sql

package database

import (
	"context"
)

const deleteTable = `-- name: DeleteTable :exec
TRUNCATE TABLE feed_follows, feeds, users
`

func (q *Queries) DeleteTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTable)
	return err
}
